CREATE TABLE [OP].[tblBonusProof] (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    EventID BIGINT NOT NULL,
    EventUserID BIGINT NOT NULL,
    Platform NVARCHAR(50) NOT NULL,
    MediaUrl NVARCHAR(500) NOT NULL,
    StatusID SMALLINT NOT NULL DEFAULT 0, -- 0: Pending, 1: Approved, 2: Rejected
    ReviewerUserID BIGINT NULL,
    ReviewDate DATETIME NULL,
    createdAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    updatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
GO
