name: Deploy Backend to Test Environment

on:
  push:
    branches:
      - test

env:
  AZURE_FUNCTIONAPP_NAME: 'eventjoy-test-api'
  AZURE_RESOURCE_GROUP: 'eventjoy-test-api_group'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'         
  DOTNET_VERSION: '8.0.x'                     

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd

      - name: 'Zip the output'
        shell: pwsh
        run: |
          Compress-Archive -Path ./output/* -DestinationPath ./publish.zip

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Functions via CLI'
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az functionapp deployment source config-zip -g ${{ env.AZURE_RESOURCE_GROUP }} -n ${{ env.AZURE_FUNCTIONAPP_NAME }} --src ./publish.zip

